# Generated by Django 5.2.8 on 2025-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gusto', models.CharField(max_length=30)),
                ('tamanio', models.CharField(max_length=30)),
            ],
        ),
    ]
