# Generated by Django 5.2.8 on 2025-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_pizzas'),
        ),
    ]
