# Generated by Django 5.2.8 on 2025-12-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_pizza_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='precio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
